
package com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "tmfFault", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
public class FaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MeldingType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMsg(String message, MeldingType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMsg(String message, MeldingType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.MeldingType
     */
    public MeldingType getFaultInfo() {
        return faultInfo;
    }

}
