
package com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OphaalService", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OphaalService {


    /**
     * 
     * @param meldingKenmerk
     * @param tmfKenmerk
     * @param meldingStatusRequest
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.TerugmeldResponseTypeList
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "statusResponseList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
    @RequestWrapper(localName = "ophalenMeldingStatus", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenMeldingStatusRequestType")
    @ResponseWrapper(localName = "ophalenMeldingStatusResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenStatusResponseType")
    public TerugmeldResponseTypeList ophalenMeldingStatus(
        @WebParam(name = "meldingStatusRequest", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        OphalenStatusRequestType meldingStatusRequest,
        @WebParam(name = "meldingKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        String meldingKenmerk,
        @WebParam(name = "tmfKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        String tmfKenmerk)
        throws FaultMsg
    ;

    /**
     * 
     * @param meldingKenmerk
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.TerugmeldMetaType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "meldingMetaData", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
    @RequestWrapper(localName = "ophalenMeldingKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenMeldingKenmerkRequestType")
    @ResponseWrapper(localName = "ophalenMeldingKenmerkResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenMeldingKenmerkResponseType")
    public TerugmeldMetaType ophalenMeldingKenmerk(
        @WebParam(name = "meldingKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        String meldingKenmerk)
        throws FaultMsg
    ;

    /**
     * 
     * @param tmfKenmerk
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.StatusTypeList
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "kenmerkResponseList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
    @RequestWrapper(localName = "ophalenTmfKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenTmfKenmerkRequestType")
    @ResponseWrapper(localName = "ophalenTmfKenmerkResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenTmfKenmerkResponseType")
    public StatusTypeList ophalenTmfKenmerk(
        @WebParam(name = "tmfKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        String tmfKenmerk)
        throws FaultMsg
    ;

    /**
     * 
     * @param totDatum
     * @param nieuweStatus
     * @param vanDatum
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.MededelingTypeList
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "mededelingResponseList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
    @RequestWrapper(localName = "ophalenMededeling", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenMededelingRequestType")
    @ResponseWrapper(localName = "ophalenMededelingResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite.OphalenMededelingResponseType")
    public MededelingTypeList ophalenMededeling(
        @WebParam(name = "nieuweStatus", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        String nieuweStatus,
        @WebParam(name = "vanDatum", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        XMLGregorianCalendar vanDatum,
        @WebParam(name = "totDatum", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1.xsd")
        XMLGregorianCalendar totDatum)
        throws FaultMsg
    ;

}
