
package com.ovsoftware.ictu.osb.gateway.tmfcore.wus.wuslite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ophaalService", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1", wsdlLocation = "file:/C:/projects/osb-tmf/tmfGenerateWebServices/wsdl/ophaalService-servicebinding.wsdl")
public class OphaalService_Service
    extends Service
{

    private final static URL OPHAALSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/projects/osb-tmf/tmfGenerateWebServices/wsdl/ophaalService-servicebinding.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        OPHAALSERVICE_WSDL_LOCATION = url;
    }

    public OphaalService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OphaalService_Service() {
        super(OPHAALSERVICE_WSDL_LOCATION, new QName("http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1", "ophaalService"));
    }

    /**
     * 
     * @return
     *     returns OphaalService
     */
    @WebEndpoint(name = "ophaalServiceSOAP")
    public OphaalService getOphaalServiceSOAP() {
        return (OphaalService)super.getPort(new QName("http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1", "ophaalServiceSOAP"), OphaalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OphaalService
     */
    @WebEndpoint(name = "ophaalServiceSOAP")
    public OphaalService getOphaalServiceSOAP(WebServiceFeature... features) {
        return (OphaalService)super.getPort(new QName("http://wus.tmf.gbo.overheid.nl/wsdl/ophaalService-V1.1", "ophaalServiceSOAP"), OphaalService.class, features);
    }

}
