CREATE TABLE RTMF_CACHE
 ( KEY             VARCHAR2(256)
 , DATEADDED       DATE
 , TMFDATEMODIFIED DATE
 , TMF             VARCHAR2(1)
 , BEVRAAGBAARTMF  VARCHAR2(1)
 , GMDATEMODIFIED  DATE
 , GM              VARCHAR2(1)
 , BEVRAAGBAARGM   VARCHAR2(1)
 , STUFPATH        VARCHAR2(1024)
 , OBJECTNAAM      VARCHAR2(1024)
 )
/

CREATE INDEX IND_RTMF_CACHE_PK
  ON RTMF_CACHE( KEY )
/

CREATE INDEX IND_RTMF_CACHE_01
  ON RTMF_CACHE( DATEADDED )
/

CREATE INDEX IND_RTMF_CACHE_02
  ON RTMF_CACHE( TMFDATEMODIFIED )
/


CREATE INDEX IND_RTMF_CACHE_03
  ON RTMF_CACHE( GMDATEMODIFIED )
/
