
package com.ovsoftware.ictu.osb.gateway.tmfcore.ebms.wuslite;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "tmf-aanmelden", targetNamespace = "http://tmfportal.ovsoftware.com/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TmfAanmelden {


    /**
     * 
     * @param objectIdentificatie
     * @param meldingKenmerk
     * @param contactInfo
     * @param basisRegistratie
     * @param toelichting
     * @param attachment
     * @param attributen
     * @param tijdstempelAanlevering
     * @param objectTag
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod(action = "A04000000000046-tmf-aanmelden-terugmelding-https---s794.nxs.nl-corvus-httpd-ebms-inbound")
    @WebResult(name = "text", targetNamespace = "")
    @RequestWrapper(localName = "terugmelding", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.ebms.wuslite.TerugmeldingRequestType")
    @ResponseWrapper(localName = "response", targetNamespace = "http://tmfportal.ovsoftware.com/services/defaultreply.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.ebms.wuslite.Responsetype")
    public String terugmelding(
        @WebParam(name = "meldingKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String meldingKenmerk,
        @WebParam(name = "tijdstempelAanlevering", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        XMLGregorianCalendar tijdstempelAanlevering,
        @WebParam(name = "basisRegistratie", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String basisRegistratie,
        @WebParam(name = "objectTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String objectTag,
        @WebParam(name = "objectIdentificatie", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String objectIdentificatie,
        @WebParam(name = "toelichting", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String toelichting,
        @WebParam(name = "attributen", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        List<ObjectAttribuutType> attributen,
        @WebParam(name = "contactInfo", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        ContactType contactInfo,
        @WebParam(name = "attachment", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        List<AttachmentType> attachment)
        throws Fault
    ;

    /**
     * 
     * @param meldingKenmerk
     * @param toelichting
     * @param tijdstempelAanlevering
     * @param betreftTmfKenmerk
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod(action = "A04000000000046-tmf-aanmelden-intrekking-https---s794.nxs.nl-corvus-httpd-ebms-inbound")
    @WebResult(name = "text", targetNamespace = "")
    @RequestWrapper(localName = "intrekking", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.ebms.wuslite.IntrekkingRequestType")
    @ResponseWrapper(localName = "response", targetNamespace = "http://tmfportal.ovsoftware.com/services/defaultreply.xsd", className = "com.ovsoftware.ictu.osb.gateway.tmfcore.ebms.wuslite.Responsetype")
    public String intrekking(
        @WebParam(name = "meldingKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String meldingKenmerk,
        @WebParam(name = "tijdstempelAanlevering", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        XMLGregorianCalendar tijdstempelAanlevering,
        @WebParam(name = "betreftTmfKenmerk", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String betreftTmfKenmerk,
        @WebParam(name = "toelichting", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/aanmeldService-V1.1.xsd")
        String toelichting)
        throws Fault
    ;

}
