<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:osb="http://tmfportal.ovsoftware.com/services"
	xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"
	xmlns:tns="http://tmfportal.ovsoftware.com/services"
	xmlns:wsa="http://www.w3.org/2005/08/addressing"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	targetNamespace="http://tmfportal.ovsoftware.com/services"
	name="Service.wsdl">
	<wsdl:import
		namespace="http://tmfportal.ovsoftware.com/services"
		location="./Service-Abstract.wsdl" />
	<wsdl:binding name="stelselBevragenServiceBinding"
		type="osb:stelselBevragenService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsaw:UsingAddressing wsdl:required="true" />
        
		<wsdl:operation name="getObjectInfo">
			<soap:operation
				soapAction="https://s794a.nxs.nl/gob/StelselBevragenBean:http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen/getObjectInfoRequest" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="getObjectInfoFault">
				<soap:fault name="getObjectInfoFault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>


		<wsdl:operation name="bevragen">
			<soap:operation
				soapAction="https://s794a.nxs.nl/gob/StelselBevragenBean:http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen/bevragenRequest" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="bevragenFault">
				<soap:fault name="bevragenFault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>


	</wsdl:binding>
	<wsdl:service name="stelselBevragenService">
		<wsdl:documentation>
			<wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.1" />
		</wsdl:documentation>
		<wsdl:port name="stelselBevragenService"
			binding="tns:stelselBevragenServiceBinding">
			<soap:address
				location="http://tmfportal.ovsoftware.com/services" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
