
package com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "stelselBevragenService", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1", wsdlLocation = "http://tmf-core-wus/stelselCatalogus/WsdlProxy?wsName=gob/StelselBevragenBean")
public class StelselBevragenService
    extends Service
{

    private final static URL STELSELBEVRAGENSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://tmf-core-wus/stelselCatalogus/WsdlProxy?wsName=gob/StelselBevragenBean");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STELSELBEVRAGENSERVICE_WSDL_LOCATION = url;
    }

    public StelselBevragenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StelselBevragenService() {
        super(STELSELBEVRAGENSERVICE_WSDL_LOCATION, new QName("http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1", "stelselBevragenService"));
    }

    /**
     * 
     * @return
     *     returns StelselBevragen
     */
    @WebEndpoint(name = "stelselBevragenSOAP")
    public StelselBevragen getStelselBevragenSOAP() {
        return (StelselBevragen)super.getPort(new QName("http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1", "stelselBevragenSOAP"), StelselBevragen.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StelselBevragen
     */
    @WebEndpoint(name = "stelselBevragenSOAP")
    public StelselBevragen getStelselBevragenSOAP(WebServiceFeature... features) {
        return (StelselBevragen)super.getPort(new QName("http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1", "stelselBevragenSOAP"), StelselBevragen.class, features);
    }

}
