
package com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StelselBevragen", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StelselBevragen {


    /**
     * 
     * @param brTag
     * @param objectTag
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "objectInfo", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
    @RequestWrapper(localName = "getObjectInfo", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectInfoRequestType")
    @ResponseWrapper(localName = "getObjectInfoResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectInfoResponseType")
    public ObjectType getObjectInfo(
        @WebParam(name = "BRTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String brTag,
        @WebParam(name = "ObjectTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String objectTag)
        throws FaultMsg
    ;

    /**
     * 
     * @param objectId
     * @param brTag
     * @param objectTag
     * @return
     *     returns com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectValueType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "objectinstantie", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
    @RequestWrapper(localName = "bevragen", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.BevragenRequestType")
    @ResponseWrapper(localName = "bevragenResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.BevragenResponseType")
    public ObjectValueType bevragen(
        @WebParam(name = "brTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String brTag,
        @WebParam(name = "objectTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String objectTag,
        @WebParam(name = "objectId", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String objectId)
        throws FaultMsg
    ;

    /**
     * 
     * @param brTag
     * @return
     *     returns java.util.List<com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectHeaderType>
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "objectTypeList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
    @RequestWrapper(localName = "getObjectTypeList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectTypeListRequestType")
    @ResponseWrapper(localName = "getObjectTypeListResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.ObjectTypeListResponseType")
    public List<ObjectHeaderType> getObjectTypeList(
        @WebParam(name = "BRTag", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
        String brTag)
        throws FaultMsg
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.BasisregistratieType>
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "basisregistratieList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd")
    @RequestWrapper(localName = "getBasisregistratieList", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.BasisregistratieListRequestType")
    @ResponseWrapper(localName = "getBasisregistratieListResponse", targetNamespace = "http://wus.tmf.gbo.overheid.nl/wsdl/stelselBevragen-V1.1.xsd", className = "com.ovsoftware.ictu.osb.gateway.stelselcatalogus.wus.wuslite.BasisregistratieListResponseType")
    public List<BasisregistratieType> getBasisregistratieList()
        throws FaultMsg
    ;

}
