<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ebus.onefox.nl/2009/3/20" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://ebus.onefox.nl/2009/3/20" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex">
  <wsdl:types>
    <xsd:schema targetNamespace="http://ebus.onefox.nl/2009/3/20/Imports">
      <xsd:import schemaLocation="version.xsd" namespace="http://ebus.onefox.nl/2009/3/20/version"/>
      <xsd:import schemaLocation="base.xsd" namespace="http://ebus.onefox.nl/2009/3/20"/>
      <xsd:import schemaLocation="Serialization.xsd" namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
      <xsd:import schemaLocation="data.xsd" namespace="http://ebus.onefox.nl/2009/3/20/data"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="GetVersionsMsg">
    <wsdl:part name="GetVersionsMsg" element="q1:GetVersionsMsg" xmlns:q1="http://ebus.onefox.nl/2009/3/20/version"/>
  </wsdl:message>
  <wsdl:message name="GetVersionsMsg_Headers">
    <wsdl:part name="AuthInfo" element="tns:AuthInfo"/>
  </wsdl:message>
  <wsdl:message name="VersionServiceResMsg">
    <wsdl:part name="ResultMsg" element="q2:ResultMsg" xmlns:q2="http://ebus.onefox.nl/2009/3/20/version"/>
  </wsdl:message>
  <wsdl:portType name="VersionService">
    <wsdl:operation name="GetVersions">
      <wsdl:input wsaw:Action="http://ebus.onefox.nl/2009/3/20/VersionService/GetVersions" name="GetVersionsMsg" message="tns:GetVersionsMsg"/>
      <wsdl:output wsaw:Action="http://ebus.onefox.nl/2009/3/20/VersionService/GetVersionsResponse" name="VersionServiceResMsg" message="tns:VersionServiceResMsg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="VersionServiceEndpoint" type="tns:VersionService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetVersions">
      <soap:operation soapAction="http://ebus.onefox.nl/2009/3/20/VersionService/GetVersions" style="document"/>
      <wsdl:input name="GetVersionsMsg">
        <soap:header message="tns:GetVersionsMsg_Headers" part="AuthInfo" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="VersionServiceResMsg">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>